version: '3'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    command: bash -c "redis-server --appendonly yes"
    restart: on-failure
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  redis-data:
    driver: local
